spring:
  application:
    name: Eureka
server:
  port: 8760

eureka:
  client:
    fetch-registry: false  # This is a standalone Eureka server
    register-with-eureka: false  # This server doesn’t register with another Eureka server
